### ISSUE TITLE
Update versoin at hex.pm

### ISSUE THREAD

**Issue by gen1321** [maxneuvians/maple#3]
When installing from hex.pm, code generation doesn't happening.

**Comment by maxneuvians** [comment]
Good point - I have been working on it on a bit recently and redid a bunch of logic. I will clean it up and release something on hex this week, I will let you know.

**Comment by maxneuvians** [comment]
So 6 months later I have done this, I am rewriting most of the app which is why it kept getting pushed. If you are still using the package, you are a hero, if not, thanks for having tried it out.
